---
layout: archive
title: Zulip Chat Archive
permalink: /stream/113488-general/topic/catching.20and.20displaying.20an.20exception.20in.20Lean.203.html
---

<h2>Stream: <a href="https://leanprover-community.github.io/archive/stream/113488-general/index.html">general</a></h2>
<h3>Topic: <a href="https://leanprover-community.github.io/archive/stream/113488-general/topic/catching.20and.20displaying.20an.20exception.20in.20Lean.203.html">catching and displaying an exception in Lean 3</a></h3>

<hr>

<base href="https://leanprover.zulipchat.com/">

<head><link href="/style.css" rel="stylesheet"></head>

{% raw %}

<a name="317084015"></a>
<h4><a href="https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/catching%20and%20displaying%20an%20exception%20in%20Lean%203/near/317084015" class="zl"><img src="https://leanprover-community.github.io/archive/assets/img/zulip2.png" alt="view this post on Zulip"></a> David Renshaw <a href="https://leanprover-community.github.io/archive/stream/113488-general/topic/catching.20and.20displaying.20an.20exception.20in.20Lean.203.html#317084015">(Dec 21 2022 at 05:00)</a>:</h4>
<p>In Lean 3 I can do <code>try { ... } catch e =&gt; { ... }</code>. Can I do something similar in Lean 3? </p>
<p>I'm detecting that an error is getting thrown on <a href="https://github.com/leanprover-community/mathlib/blob/ba2245edf0c8bb155f1569fd9b9492a9b384cde6/src/tactic/tauto.lean#L153">this line</a>, but I don't know of a good way to examine what the error actually is.</p>



<a name="317102733"></a>
<h4><a href="https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/catching%20and%20displaying%20an%20exception%20in%20Lean%203/near/317102733" class="zl"><img src="https://leanprover-community.github.io/archive/assets/img/zulip2.png" alt="view this post on Zulip"></a> Martin Dvořák <a href="https://leanprover-community.github.io/archive/stream/113488-general/topic/catching.20and.20displaying.20an.20exception.20in.20Lean.203.html#317102733">(Dec 21 2022 at 08:08)</a>:</h4>
<p>Is the code snippet in Lean 4?</p>



<a name="317145977"></a>
<h4><a href="https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/catching%20and%20displaying%20an%20exception%20in%20Lean%203/near/317145977" class="zl"><img src="https://leanprover-community.github.io/archive/assets/img/zulip2.png" alt="view this post on Zulip"></a> David Renshaw <a href="https://leanprover-community.github.io/archive/stream/113488-general/topic/catching.20and.20displaying.20an.20exception.20in.20Lean.203.html#317145977">(Dec 21 2022 at 12:24)</a>:</h4>
<p>Oops, updated. Yes, the snippet is intended to be Lean 4. How do I do <code>try ... catch</code> in Lean 3?</p>



<a name="317147866"></a>
<h4><a href="https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/catching%20and%20displaying%20an%20exception%20in%20Lean%203/near/317147866" class="zl"><img src="https://leanprover-community.github.io/archive/assets/img/zulip2.png" alt="view this post on Zulip"></a> Alex J. Best <a href="https://leanprover-community.github.io/archive/stream/113488-general/topic/catching.20and.20displaying.20an.20exception.20in.20Lean.203.html#317147866">(Dec 21 2022 at 12:35)</a>:</h4>
<p>Perhaps <a href="https://leanprover-community.github.io/mathlib_docs/find/tactic.try_or_report_error">docs#tactic.try_or_report_error</a></p>



<a name="317160175"></a>
<h4><a href="https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/catching%20and%20displaying%20an%20exception%20in%20Lean%203/near/317160175" class="zl"><img src="https://leanprover-community.github.io/archive/assets/img/zulip2.png" alt="view this post on Zulip"></a> David Renshaw <a href="https://leanprover-community.github.io/archive/stream/113488-general/topic/catching.20and.20displaying.20an.20exception.20in.20Lean.203.html#317160175">(Dec 21 2022 at 13:39)</a>:</h4>
<p>Thanks. The reported error indicated that I should do <code>set_option trace.app_builder true</code>. After doing that I no longer need to catch the error.</p>



{% endraw %}

<hr><p>Last updated: Jan 25 2023 at 00:06 UTC</p>