---
layout: archive
title: Zulip Chat Archive
permalink: /stream/113488-general/topic/CI.20error.20in.20the.20.22run.20tests.22.20phase.html
---

<h2>Stream: <a href="https://leanprover-community.github.io/archive/stream/113488-general/index.html">general</a></h2>
<h3>Topic: <a href="https://leanprover-community.github.io/archive/stream/113488-general/topic/CI.20error.20in.20the.20.22run.20tests.22.20phase.html">CI error in the "run tests" phase</a></h3>

<hr>

<base href="https://leanprover.zulipchat.com/">

<head><link href="/style.css" rel="stylesheet"></head>

{% raw %}

<a name="264824844"></a>
<h4><a href="https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/CI%20error%20in%20the%20%22run%20tests%22%20phase/near/264824844" class="zl"><img src="https://leanprover-community.github.io/archive/assets/img/zulip2.png" alt="view this post on Zulip"></a> Rémy Degenne <a href="https://leanprover-community.github.io/archive/stream/113488-general/topic/CI.20error.20in.20the.20.22run.20tests.22.20phase.html#264824844">(Dec 14 2021 at 08:28)</a>:</h4>
<p>I have a CI error I don't understand at <a href="https://github.com/leanprover-community/mathlib/pull/10713">#10713</a> . At the<code>export as low-level text file</code> step of the <code>Run tests</code> CI, I get the error </p>
<div class="codehilite" data-code-language="Lean"><pre><span></span><code><span class="n">Run</span> <span class="n">lean</span> <span class="c1">--recursive --export=mathlib.txt src/</span>
<span class="bp">&lt;</span><span class="n">unknown</span><span class="bp">&gt;</span><span class="o">:</span><span class="mi">1</span><span class="o">:</span><span class="mi">1</span><span class="o">:</span> <span class="n">error</span><span class="o">:</span> <span class="n">unknown</span> <span class="n">declaration</span> <span class="bp">'</span><span class="n">_private.3627408217.add'</span>
<span class="n">Error</span><span class="o">:</span> <span class="n">Process</span> <span class="n">completed</span> <span class="k">with</span> <span class="n">exit</span> <span class="n">code</span> <span class="mi">1</span><span class="bp">.</span>
</code></pre></div>
<p>(You can go to the PR and click on <code>details</code> on the failing CI for more info)<br>
I ran the tests several times because I thought it might go away on its own, but the error stays. Does anyone know what I should do about it?</p>



<a name="264826445"></a>
<h4><a href="https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/CI%20error%20in%20the%20%22run%20tests%22%20phase/near/264826445" class="zl"><img src="https://leanprover-community.github.io/archive/assets/img/zulip2.png" alt="view this post on Zulip"></a> Eric Wieser <a href="https://leanprover-community.github.io/archive/stream/113488-general/topic/CI.20error.20in.20the.20.22run.20tests.22.20phase.html#264826445">(Dec 14 2021 at 08:45)</a>:</h4>
<p>Might be a cache bug - merging master might be enough to invalidate whatever bad cache it's using</p>



<a name="264826643"></a>
<h4><a href="https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/CI%20error%20in%20the%20%22run%20tests%22%20phase/near/264826643" class="zl"><img src="https://leanprover-community.github.io/archive/assets/img/zulip2.png" alt="view this post on Zulip"></a> Rémy Degenne <a href="https://leanprover-community.github.io/archive/stream/113488-general/topic/CI.20error.20in.20the.20.22run.20tests.22.20phase.html#264826643">(Dec 14 2021 at 08:48)</a>:</h4>
<p>Thanks I'll try that</p>



{% endraw %}

<hr><p>Last updated: Jan 25 2023 at 00:06 UTC</p>