---
layout: archive
title: Zulip Chat Archive
permalink: /stream/113489-new-members/topic/Strange.20error.20in.20.22Lint.20mathlib.22.20check.html
---

<h2>Stream: <a href="https://leanprover-community.github.io/archive/stream/113489-new-members/index.html">new members</a></h2>
<h3>Topic: <a href="https://leanprover-community.github.io/archive/stream/113489-new-members/topic/Strange.20error.20in.20.22Lint.20mathlib.22.20check.html">Strange error in "Lint mathlib" check</a></h3>

<hr>

<base href="https://leanprover.zulipchat.com/">

<head><link href="/style.css" rel="stylesheet"></head>

{% raw %}

<a name="281818781"></a>
<h4><a href="https://leanprover.zulipchat.com/#narrow/stream/113489-new%20members/topic/Strange%20error%20in%20%22Lint%20mathlib%22%20check/near/281818781" class="zl"><img src="https://leanprover-community.github.io/archive/assets/img/zulip2.png" alt="view this post on Zulip"></a> Sebastian Monnet <a href="https://leanprover-community.github.io/archive/stream/113489-new-members/topic/Strange.20error.20in.20.22Lint.20mathlib.22.20check.html#281818781">(May 10 2022 at 12:51)</a>:</h4>
<p>I tried replacing some lemma/def arguments with variables in PR <a href="https://github.com/leanprover-community/mathlib/pull/13307">#13307</a>, and it seems to have broken something, since the Lint mathlib check is failing. I don't understand the error message, though. It says: </p>
<div class="codehilite" data-code-language="Lean"><pre><span></span><code><span class="n">Run</span> <span class="n">set</span> <span class="bp">-</span><span class="n">o</span> <span class="n">pipefail</span>
<span class="n">info</span><span class="o">:</span> <span class="n">downloading</span> <span class="n">installer</span>
<span class="n">curl</span><span class="o">:</span> <span class="o">(</span><span class="mi">22</span><span class="o">)</span> <span class="n">The</span> <span class="n">requested</span> <span class="n">URL</span> <span class="n">returned</span> <span class="n">error</span><span class="o">:</span> <span class="mi">404</span>
<span class="n">elan</span><span class="o">:</span> <span class="n">command</span> <span class="n">failed</span><span class="o">:</span> <span class="n">curl</span> <span class="bp">-</span><span class="n">sSfL</span> <span class="n">https</span><span class="o">:</span><span class="bp">//</span><span class="n">github.com</span><span class="bp">/</span><span class="n">leanprover</span><span class="bp">/</span><span class="n">elan</span><span class="bp">/</span><span class="n">releases</span><span class="bp">/</span><span class="n">download</span><span class="bp">//</span><span class="n">elan</span><span class="bp">-</span><span class="n">x86_64</span><span class="bp">-</span><span class="n">unknown</span><span class="bp">-</span><span class="n">linux</span><span class="bp">-</span><span class="n">gnu.tar.gz</span> <span class="bp">-</span><span class="n">o</span> <span class="bp">/</span><span class="n">tmp</span><span class="bp">/</span><span class="n">tmp.B0Iqdr9jt0</span><span class="bp">/</span><span class="n">elan</span><span class="bp">-</span><span class="n">init.tar.gz</span>
<span class="n">Error</span><span class="o">:</span> <span class="n">Process</span> <span class="n">completed</span> <span class="k">with</span> <span class="n">exit</span> <span class="n">code</span> <span class="mi">1</span><span class="bp">.</span>
</code></pre></div>
<p>Does anyone know what this means, or how I can fix it?</p>



<a name="281819537"></a>
<h4><a href="https://leanprover.zulipchat.com/#narrow/stream/113489-new%20members/topic/Strange%20error%20in%20%22Lint%20mathlib%22%20check/near/281819537" class="zl"><img src="https://leanprover-community.github.io/archive/assets/img/zulip2.png" alt="view this post on Zulip"></a> Eric Wieser <a href="https://leanprover-community.github.io/archive/stream/113489-new-members/topic/Strange.20error.20in.20.22Lint.20mathlib.22.20check.html#281819537">(May 10 2022 at 12:56)</a>:</h4>
<p>You need to merge master to get some fixes to the CI setup</p>



<a name="281827746"></a>
<h4><a href="https://leanprover.zulipchat.com/#narrow/stream/113489-new%20members/topic/Strange%20error%20in%20%22Lint%20mathlib%22%20check/near/281827746" class="zl"><img src="https://leanprover-community.github.io/archive/assets/img/zulip2.png" alt="view this post on Zulip"></a> Sebastian Monnet <a href="https://leanprover-community.github.io/archive/stream/113489-new-members/topic/Strange.20error.20in.20.22Lint.20mathlib.22.20check.html#281827746">(May 10 2022 at 14:00)</a>:</h4>
<p><span class="user-mention" data-user-id="310045">@Eric Wieser</span>  I tried merging from master in VSCode and then syncing, but it doesn't seem to have done anything. I'm not sure whether I did it wrong or not</p>



<a name="281827856"></a>
<h4><a href="https://leanprover.zulipchat.com/#narrow/stream/113489-new%20members/topic/Strange%20error%20in%20%22Lint%20mathlib%22%20check/near/281827856" class="zl"><img src="https://leanprover-community.github.io/archive/assets/img/zulip2.png" alt="view this post on Zulip"></a> Eric Wieser <a href="https://leanprover-community.github.io/archive/stream/113489-new-members/topic/Strange.20error.20in.20.22Lint.20mathlib.22.20check.html#281827856">(May 10 2022 at 14:01)</a>:</h4>
<p>The error message is from github not vscode</p>



<a name="281827879"></a>
<h4><a href="https://leanprover.zulipchat.com/#narrow/stream/113489-new%20members/topic/Strange%20error%20in%20%22Lint%20mathlib%22%20check/near/281827879" class="zl"><img src="https://leanprover-community.github.io/archive/assets/img/zulip2.png" alt="view this post on Zulip"></a> Eric Wieser <a href="https://leanprover-community.github.io/archive/stream/113489-new-members/topic/Strange.20error.20in.20.22Lint.20mathlib.22.20check.html#281827879">(May 10 2022 at 14:01)</a>:</h4>
<p>You'll need to push after merging and wait to see if it fixes github</p>



<a name="281828677"></a>
<h4><a href="https://leanprover.zulipchat.com/#narrow/stream/113489-new%20members/topic/Strange%20error%20in%20%22Lint%20mathlib%22%20check/near/281828677" class="zl"><img src="https://leanprover-community.github.io/archive/assets/img/zulip2.png" alt="view this post on Zulip"></a> Sebastian Monnet <a href="https://leanprover-community.github.io/archive/stream/113489-new-members/topic/Strange.20error.20in.20.22Lint.20mathlib.22.20check.html#281828677">(May 10 2022 at 14:07)</a>:</h4>
<p>Right yeah, I made a new commit after trying to merge from master and it still failed</p>



<a name="281828881"></a>
<h4><a href="https://leanprover.zulipchat.com/#narrow/stream/113489-new%20members/topic/Strange%20error%20in%20%22Lint%20mathlib%22%20check/near/281828881" class="zl"><img src="https://leanprover-community.github.io/archive/assets/img/zulip2.png" alt="view this post on Zulip"></a> Bryan Gin-ge Chen <a href="https://leanprover-community.github.io/archive/stream/113489-new-members/topic/Strange.20error.20in.20.22Lint.20mathlib.22.20check.html#281828881">(May 10 2022 at 14:08)</a>:</h4>
<p>I don't see a merge commit on the PR page? Are you sure you pushed the merge commit to GitHub? <a href="https://github.com/leanprover-community/mathlib/pull/13307">https://github.com/leanprover-community/mathlib/pull/13307</a></p>



<a name="281829688"></a>
<h4><a href="https://leanprover.zulipchat.com/#narrow/stream/113489-new%20members/topic/Strange%20error%20in%20%22Lint%20mathlib%22%20check/near/281829688" class="zl"><img src="https://leanprover-community.github.io/archive/assets/img/zulip2.png" alt="view this post on Zulip"></a> Sebastian Monnet <a href="https://leanprover-community.github.io/archive/stream/113489-new-members/topic/Strange.20error.20in.20.22Lint.20mathlib.22.20check.html#281829688">(May 10 2022 at 14:14)</a>:</h4>
<p><span class="user-mention silent" data-user-id="123965">Bryan Gin-ge Chen</span> <a href="#narrow/stream/113489-new-members/topic/Strange.20error.20in.20.22Lint.20mathlib.22.20check/near/281828881">said</a>:</p>
<blockquote>
<p>I don't see a merge commit on the PR page? Are you sure you pushed the merge commit to GitHub? <a href="https://github.com/leanprover-community/mathlib/pull/13307">https://github.com/leanprover-community/mathlib/pull/13307</a></p>
</blockquote>
<p>I am very unsure. What I did was: clicked on the little ... in the "Source Control" of VSCode, went to Branch -&gt; Merge Branch, selected the branch origin/master, made some trivial change to my code so that it let me make a new commit, and then committed it</p>



<a name="281830324"></a>
<h4><a href="https://leanprover.zulipchat.com/#narrow/stream/113489-new%20members/topic/Strange%20error%20in%20%22Lint%20mathlib%22%20check/near/281830324" class="zl"><img src="https://leanprover-community.github.io/archive/assets/img/zulip2.png" alt="view this post on Zulip"></a> Bryan Gin-ge Chen <a href="https://leanprover-community.github.io/archive/stream/113489-new-members/topic/Strange.20error.20in.20.22Lint.20mathlib.22.20check.html#281830324">(May 10 2022 at 14:19)</a>:</h4>
<p>Was it this commit? <a href="https://github.com/leanprover-community/mathlib/pull/13307/commits/b453a429dce7169742096b202842fd2596c15ca3">https://github.com/leanprover-community/mathlib/pull/13307/commits/b453a429dce7169742096b202842fd2596c15ca3</a></p>
<p>If so, it doesn't look like it contains a merge with the latest <code>master</code>. You might have to fetch the latest version of master before merging. <code>git fetch &amp;&amp; git merge origin/master</code> is what I usually run from the command line.</p>



<a name="281833216"></a>
<h4><a href="https://leanprover.zulipchat.com/#narrow/stream/113489-new%20members/topic/Strange%20error%20in%20%22Lint%20mathlib%22%20check/near/281833216" class="zl"><img src="https://leanprover-community.github.io/archive/assets/img/zulip2.png" alt="view this post on Zulip"></a> Sebastian Monnet <a href="https://leanprover-community.github.io/archive/stream/113489-new-members/topic/Strange.20error.20in.20.22Lint.20mathlib.22.20check.html#281833216">(May 10 2022 at 14:38)</a>:</h4>
<p>It worked! Thank you both</p>



{% endraw %}

<hr><p>Last updated: Jan 25 2023 at 00:06 UTC</p>