[
    {
        "content": "<p>These are the changes: <a href=\"https://github.com/leanprover-community/mathlib4/compare/6d86a6ac7aa6eae79181b6bae1fca53be16d2379..090a8a08255671e5d06f2b22131421871f2b373f\">https://github.com/leanprover-community/mathlib4/compare/6d86a6ac7aa6eae79181b6bae1fca53be16d2379..090a8a08255671e5d06f2b22131421871f2b373f</a></p>",
        "id": 321269913,
        "sender_full_name": "Gabriel Ebner",
        "timestamp": 1673648958
    },
    {
        "content": "<p>Not yet sure what's going on here.  After the update mathport takes about two hours and fails in <code>data.polynomial.mirror</code> <a href=\"https://github.com/leanprover-community/mathport/actions/runs/3913731949/jobs/6689971655\">https://github.com/leanprover-community/mathport/actions/runs/3913731949/jobs/6689971655</a></p>",
        "id": 321270108,
        "sender_full_name": "Gabriel Ebner",
        "timestamp": 1673649045
    },
    {
        "content": "<p>Are we sure this is due to mathlib4 and not mathlib3?</p>",
        "id": 321270327,
        "sender_full_name": "Eric Wieser",
        "timestamp": 1673649135
    },
    {
        "content": "<p>We update mathlib4 12x more frequently than mathlib3.  There was no mathlib3 update between the succeeding and failing mathport runs.</p>",
        "id": 321270404,
        "sender_full_name": "Gabriel Ebner",
        "timestamp": 1673649182
    },
    {
        "content": "<p>Looks like checking the definition in the kernel takes forever.  Unfortunately we can't set a timeout, because the timeout is reported as an uncatchable C++ exception.  <a href=\"https://github.com/leanprover/lean4/pull/2036\">https://github.com/leanprover/lean4/pull/2036</a></p>",
        "id": 321295828,
        "sender_full_name": "Gabriel Ebner",
        "timestamp": 1673666763
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"110043\">@Gabriel Ebner</span> Is there anything that stands out to you?</p>",
        "id": 321297293,
        "sender_full_name": "Johan Commelin",
        "timestamp": 1673668363
    },
    {
        "content": "<p>I wouldn't know where to start looking for an issue. Is it worth bisecting the failure, to see which of these files exactly is causing a problem?</p>",
        "id": 321297386,
        "sender_full_name": "Johan Commelin",
        "timestamp": 1673668493
    },
    {
        "content": "<p>With the dubious translations, I expect this failure mode to occur again sooner or later.</p>",
        "id": 321297486,
        "sender_full_name": "Gabriel Ebner",
        "timestamp": 1673668597
    },
    {
        "content": "<p>Aha, so you think it might be an issue of a missing <code>â‚“</code>?</p>",
        "id": 321297591,
        "sender_full_name": "Johan Commelin",
        "timestamp": 1673668710
    }
]