[
    {
        "content": "<p>I assigned <code>try_for</code> to <span class=\"user-mention\" data-user-id=\"130575\">@Siddharth Bhat</span> in Providence thinking it would be a simple tactic, but it turned out to be very complicated and <a href=\"https://github.com/leanprover/lean4/pull/1364\">https://github.com/leanprover/lean4/pull/1364</a> stalled. What is the status of this feature? Does it need special support from the compiler / interpreter? In short: how do you run programs with a timeout and cancel them later? How does the server handle this (surely it comes up already)?</p>",
        "id": 300260768,
        "sender_full_name": "Mario Carneiro",
        "timestamp": 1663887103
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"110049\">@Mario Carneiro</span> Here's the PR which tried to add the feature into the kernel: <a href=\"https://github.com/leanprover/lean4/pull/1364\">https://github.com/leanprover/lean4/pull/1364</a></p>\n<p>I didn't have the cycles then to debug what was going wrong with some of the failing test cases [I suspected that perhaps the heartbeat counter was too low, now that we track a heartbeat \"accurately\". But this guess could be wildly off].</p>\n<p>I closed the PR, with the intention of getting back to it post LLVM merge. That's currently dragging on figuring out why the <em>windows</em> build is broken :)</p>",
        "id": 300323966,
        "sender_full_name": "Siddharth Bhat",
        "timestamp": 1663925772
    }
]