[
    {
        "content": "<p><a href=\"https://leanprover-community.github.io/mathlib_docs/find/assert_not_exists\">docs#assert_not_exists</a> is failing in <a href=\"https://github.com/leanprover-community/mathlib/pull/17904\">#17904</a> because the unique name being generated appears to only be unique within the environment at that point in time. It seems that there's a uniqueness diamond where two files containing supposedly unique names can't be imported simultaneously because of a name clash.</p>\n<p>Is there some way to get the current filename and line number to reduce the chance of such a clash?</p>",
        "id": 315482364,
        "sender_full_name": "Eric Wieser",
        "timestamp": 1670886608
    },
    {
        "content": "<p>The offending lines are here: <a href=\"https://github.com/leanprover-community/mathlib/blob/fc2ed6f838ce7c9b7c7171e58d78eaf7b438fb0e/src/tactic/assert_exists.lean#L64-L65\">https://github.com/leanprover-community/mathlib/blob/fc2ed6f838ce7c9b7c7171e58d78eaf7b438fb0e/src/tactic/assert_exists.lean#L64-L65</a></p>",
        "id": 315482431,
        "sender_full_name": "Eric Wieser",
        "timestamp": 1670886643
    },
    {
        "content": "<p>(cc <span class=\"user-mention\" data-user-id=\"488648\">@Xavier Roblot</span>, just to let you know I understand why your PR is failing)</p>",
        "id": 315482626,
        "sender_full_name": "Eric Wieser",
        "timestamp": 1670886724
    },
    {
        "content": "<p><a href=\"https://github.com/leanprover-community/mathlib/pull/17916\">#17916</a> is my workaround to at least reduce the probability of this happening.</p>",
        "id": 315483497,
        "sender_full_name": "Eric Wieser",
        "timestamp": 1670887158
    }
]