[
    {
        "content": "<p>I just stumbled on the following issue:</p>\n<div class=\"codehilite\"><pre><span></span>open tactic\nmeta def test : tactic unit := failed\nmeta def tac (_ : interactive.parse test) := skip\nrun_cmd add_interactive [`tac]\nexample : true := by tac.\n-- vm check failed: is_closure(o) (possibly due to incorrect axioms, or sorry)\n</pre></div>\n\n\n<p>The problem appears to be that nothing catches an error thrown in a tactic when it is passed through the <code>of_tactic</code> builtin function</p>",
        "id": 133093024,
        "sender_full_name": "Mario Carneiro",
        "timestamp": 1535672201
    }
]