[
    {
        "content": "<p>I have this code</p>\n<div class=\"codehilite\" data-code-language=\"import\"><pre><span></span><code>#check sub_self\n\nexample (x : ℤ) : x * 0 = 0 :=\ncalc\n  x * 0 = x * (1 - 1)   : by rw sub_self\n  ...   = x * 1 - x * 1 : mul_sub x 1 1\n  ...   = 0             : sub_self (x * 1)\n</code></pre></div>\n<p>I run <code>lean filename.lean</code></p>\n<p>And get</p>\n<p><code>sub_self : ∀ (a : ?M_1), a - a = 0</code></p>\n<p>I can't tell if this is telling my attempted proof has failed. Normally I get <code>error</code> or similar if my proof is incorrect. Is this merely an informative message?</p>",
        "id": 262216954,
        "sender_full_name": "Dan Piponi",
        "timestamp": 1637461221
    }
]